### ISSUE TITLE
react-scripts must be bumped to >5.0.0 to avoid openssl issue

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/AuroReactDemo#48]
## Describe the bug
There is a bug with react-scripts < 5.0.0 that results in the following error upon running npm run start:

## To Reproduce
```
git clone https://github.com/AlaskaAirlines/AuroReactDemo.git
cd AuroReactDemo
npm i
npm run start
```

Result:
```
Error: error:0308010C:digital envelope routines::unsupported
```

## Expected behavior
``` npm run start``` should spin up a webserver.

## Screenshots
<img width="902" alt="image" src="https://github.com/AlaskaAirlines/AuroReactDemo/assets/7005799/80c1ace3-6491-4462-a28d-15af346d938e">

**Comment by blackfalcon** [comment]
@gusnaughton what version of Node are you running? I typically still use Node 12 for this.

**Comment by Patrick-Daly-AA** [comment]
Thank you for creating this issue.  We're interested in recommendations and community support in updating this demo environment, as we haven't looked into it in ~2 years.
